version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: unless-stopped
    volumes:
      - ./bot.db:/app/bot.db  # Монтируем базу данных
      - ./.env:/app/.env      # Монтируем переменные окружения
    environment:
      - TZ=Europe/Moscow      # Устанавливаем часовой пояс
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge 